### ISSUE TITLE
MC 1.19.1 upgrade

### ISSUE THREAD

**Issue by John-Paul-R** [John-Paul-R/Essential-Commands#138]
I believe some mixins are broken

```
java.lang.NoSuchFieldError: field_11735
        at com.fibermc.essentialcommands.PlayerData.setAfk(PlayerData.java:211)
        at com.fibermc.essentialcommands.PlayerData.onTickEnd(PlayerData.java:259)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)
        at com.fibermc.essentialcommands.PlayerDataManager.tick(PlayerDataManager.java:120)
        at com.fibermc.essentialcommands.PlayerDataManager.lambda$init$0(PlayerDataManager.java:52)
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62)
        at net.minecraft.server.MinecraftServer.handler$zkp000$onEndTick(MinecraftServer.java:4821)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857)
        at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2885)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by John-Paul-R** [comment]
Completed with release [0.28.0-mc1.19.1](https://github.com/John-Paul-R/Essential-Commands/releases/tag/0.28.0-mc1.19.1).
