### ISSUE TITLE
Fabric1.18.2 RTP doesn't work when using with BYG mod

### ISSUE THREAD

**Issue by 5ur3z** [John-Paul-R/Essential-Commands#150]
[RTP Location Calculator Thread/ERROR]: Uncaught exception in thread "RTP Location Calculator Thread"
java.lang.IllegalArgumentException: bound must be greater than origin
        at jdk.internal.util.random.RandomSupport.checkRange(RandomSupport.java:232) ~[?:?]
        at java.util.random.RandomGenerator.nextInt(RandomGenerator.java:679) ~[?:?]
        at com.fibermc.essentialcommands.commands.RandomTeleportCommand.exec(RandomTeleportCommand.java:116) ~[essential_commands-0.24.5-mc1.18.2.jar:?]
        at com.fibermc.essentialcommands.commands.RandomTeleportCommand.exec(RandomTeleportCommand.java:101) ~[essential_commands-0.24.5-mc1.18.2.jar:?]
        at com.fibermc.essentialcommands.commands.RandomTeleportCommand$1.run(RandomTeleportCommand.java:75) ~[essential_commands-0.24.5-mc1.18.2.jar:?]

**Comment by John-Paul-R** [comment]
I think I was silly when I first read this.

Is your `RTP_MIN_RADIUS` less than your `RTP_RADIUS`, by chance?
