### ISSUE TITLE
Crashes when going to be AFK

### ISSUE THREAD

**Issue by Moe23333** [John-Paul-R/Essential-Commands#152]
Minecraft Version: 1.19.2
Loader Version: Quilt 0.18.1-beta.16
Java Version: Eclipse Adoptium JRE 17.0.6-beta 64bit
Essential Commands Version: 0.30.0-mc1.19+20221115221354 ([4c3d2b2](https://github.com/John-Paul-R/Essential-Commands/commit/4c3d2b25d4eb592c5e5d00eabe16ad75c9f8767f)), downloaded from [GitHub Actions](https://github.com/John-Paul-R/Essential-Commands/actions/runs/3381645450)

Minecraft Crash Report
```
Time: 2022-11-22 16:57:57
Description: Exception in server tick loop

java.lang.NoSuchFieldError: field_11735
 at com.fibermc.essentialcommands.playerdata.PlayerData.setAfk(PlayerData.java:225)
 at com.fibermc.essentialcommands.playerdata.PlayerData.onTickEnd(PlayerData.java:273)
 at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source)
 at com.fibermc.essentialcommands.playerdata.PlayerDataManager.tick(PlayerDataManager.java:122)
 at com.fibermc.essentialcommands.playerdata.PlayerDataManager.lambda$init$0(PlayerDataManager.java:54)
 at org.quiltmc.qsl.lifecycle.api.event.ServerTickEvents.lambda$static$2(ServerTickEvents.java:53)
 at net.minecraft.server.MinecraftServer.handler$cjl000$endServerTick(MinecraftServer.java:6828)
 at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857)
 at net.minecraft.class_1132.method_3748(class_1132.java:98)
 at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
 at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
 at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by John-Paul-R** [comment]
It looks like you're using a version of Essential Commands built for 1.19, you will need one built for 1.19.2, because that is the version of your server.

**Comment by Moe23333** [comment]
> It looks like you're using a version of Essential Commands built for 1.19, you will need one built for 1.19.2, because that is the version of your server.

Ah… I'm sorry for that.

**Comment by John-Paul-R** [comment]
All good!
