### ISSUE TITLE
(w/ FancyClear) java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.LoaderOptions.setProcessComments(boolean)'

### ISSUE THREAD

**Issue by h266579110** [John-Paul-R/Essential-Commands#155]
> Time: 2022-11-29 00:50:25
> Description: Exception in server tick loop
> 
> java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.LoaderOptions.setProcessComments(boolean)'
> 	at api.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:80)
> 	at api.configuration.file.FileConfiguration.load(FileConfiguration.java:146)
> 	at api.configuration.file.FileConfiguration.load(FileConfiguration.java:114)
> 	at api.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:286)
> 	at com.daxton.fancyclear.config.FileConfig.execute(FileConfig.java:17)
> 	at com.daxton.fancyclear.task.server.Start.execute(Start.java:16)
> 	at com.daxton.fancyclear.FancyClear.lambda$onInitialize$1(FancyClear.java:39)
> 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
> 	at net.minecraft.server.MinecraftServer.handler$dhf000$afterSetupServer(MinecraftServer.java:7301)
> 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
> 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
	
FABRIC 1.19.2

**Comment by John-Paul-R** [comment]
likely incompat with `FancyClear`

```
at com.daxton.fancyclear.FancyClear.lambda$onInitialize$1(FancyClear.java:39)
```

can look into this in more detail later today

**Comment by John-Paul-R** [comment]
Hm, I'd initially thought that the version of snakeyaml that I package with EC didn't have the method that `FancyClear` was looking for, but the version I package, `v1.33` does seem to have `LoaderOptions.setProcessComments(boolean)`.

Not 100% sure what is going wrong at present.
