### ISSUE TITLE
`/rtp` bug

### ISSUE THREAD

**Issue by lgc2333** [John-Paul-R/Essential-Commands#202]
```
[04:15:21] [RTP Location Calculator Thread/ERROR]: Uncaught exception in thread "RTP Location Calculator Thread"
java.lang.NullPointerException: Cannot invoke "com.fibermc.essentialcommands.types.MinecraftLocation.intPos()" because the return value of "com.fibermc.essentialcommands.WorldDataManager.getSpawn()" is null
 at com.fibermc.essentialcommands.commands.RandomTeleportCommand.exec(RandomTeleportCommand.java:114) ~[essential_commands-0.32.0-mc1.19.4.jar:?]
 at com.fibermc.essentialcommands.commands.RandomTeleportCommand$1.run(RandomTeleportCommand.java:88) ~[essential_commands-0.32.0-mc1.19.4.jar:?]
```

**Comment by lgc2333** [comment]
viaversion dump: https://dump.viaversion.com/9dec83360345d10fc61992b200e6ce5db83fc480065a097aa3673f4e97e066ff
(server version, fabric version & modlist...)

**Comment by John-Paul-R** [comment]
Make sure you've set a spawn with `/spawn set` lmk if the issue persists after.

This lack of in-game error message will be resolved with the next release.

**Comment by John-Paul-R** [comment]
Bugfix made in #197
