### ISSUE TITLE
Server crash 1.19.2

### ISSUE THREAD

**Issue by XionioXMaster** [John-Paul-R/Essential-Commands#219]
Crash-report: https://mcpaste.io/12214cdb455952fc

Last log info:

[18:18:45] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: class net.minecraft.class_7417$1 cannot be cast to class net.minecraft.class_2588 (net.minecraft.class_7417$1 and net.minecraft.class_2588 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1807f5a7)
	at net.minecraft.class_3324.handler$ddj000$joinleavemessages$filterBroadCastMessages(class_3324.java:11004) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_43514(class_3324.java) ~[server-intermediary.jar:?]
	at com.fibermc.essentialcommands.playerdata.PlayerData.setAfk(PlayerData.java:221) ~[essential_commands-0.33.2-mc1.19.2.jar:?]
	at com.fibermc.essentialcommands.playerdata.PlayerData.onTickEnd(PlayerData.java:270) ~[essential_commands-0.33.2-mc1.19.2.jar:?]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[?:?]
	at com.fibermc.essentialcommands.playerdata.PlayerDataManager.tick(PlayerDataManager.java:130) ~[essential_commands-0.33.2-mc1.19.2.jar:?]
	at com.fibermc.essentialcommands.playerdata.PlayerDataManager.lambda$init$0(PlayerDataManager.java:59) ~[essential_commands-0.33.2-mc1.19.2.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62) ~[fabric-lifecycle-events-v1-2.2.4+1b46dc7890-db0fd3f5dc0d6099.jar:?]
	at net.minecraft.server.MinecraftServer.handler$coc002$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:10821) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zno000$carpet$modifiedRunLoop(MinecraftServer.java:7385) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by John-Paul-R** [comment]
Thanks for the report! Have you been able to reproduce this? If so, do you know when it happens? I cannot currently reproduce this issue on EC `0.33.2-mc1.19.2` with `/afk`.

**Comment by John-Paul-R** [comment]
It is possible this has already been addressed, and there has been no further feedback on this issue. It may be closed any time after Aug 16 2023 if it remains inactive.
