### ISSUE TITLE
1.16.5 server crash

### ISSUE THREAD

**Issue by henryjmin** [John-Paul-R/Essential-Commands#271]
Java version: openjdk 16.0.2
```
[05:19:04] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.15.6
[05:19:04] [main/INFO]: Loading 49 mods:
	- essential_commands 0.17.0-mc1.16.5
	   |-- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.12.2
	   |-- ec-core 1.0.0-mc1.16.5
	   |    |-- fabric-permissions-api-v0 0.1-SNAPSHOT
	   |    |-- grossfabrichacks 6.1-JP7-4
	   |    |    |-- dynamicentry 0.1.3
	   |    |    |-- net_bytebuddy_byte-buddy-agent 1.11.12
	   |    |    |-- net_gudenau_lib_unsafe 1.4.3
	   |    |    \-- user11681_reflect 2.0.0
	   |    \-- placeholder-api 1.0.1+1.16
	   |-- fabric-permissions-api-v0 0.1-SNAPSHOT
	   |-- grossfabrichacks 6.1-JP7-4
	   |    |-- dynamicentry 0.1.3
	   |    |-- net_bytebuddy_byte-buddy-agent 1.11.12
	   |    |-- net_gudenau_lib_unsafe 1.4.3
	   |    \-- user11681_reflect 2.0.0
	   |-- placeholder-api 1.0.1+1.16
	   \-- playerabilitylib 1.2.2
	- fabric 0.42.0+1.16
	   |-- fabric-api-base 0.4.0+3cc0f0907d
	   |-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
	   |-- fabric-biome-api-v1 3.1.13+3cc0f0907d
	   |-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
	   |-- fabric-command-api-v1 1.1.3+3cc0f0907d
	   |-- fabric-commands-v0 0.2.3+3cc0f0907d
	   |-- fabric-containers-v0 0.1.12+3cc0f0907d
	   |-- fabric-content-registries-v0 0.2.5+3cc0f0907d
	   |-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
	   |-- fabric-dimensions-v1 2.0.8+3cc0f0907d
	   |-- fabric-entity-events-v1 1.2.4+3cc0f0907d
	   |-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
	   |-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
	   |-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
	   |-- fabric-item-api-v1 1.2.2+3cc0f0907d
	   |-- fabric-item-groups-v0 0.3.1+3cc0f0907d
	   |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-keybindings-v0 0.2.2+3cc0f0907d
	   |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
	   |-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
	   |-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
	   |-- fabric-models-v0 0.3.1+3cc0f0907d
	   |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
	   |-- fabric-networking-v0 0.3.3+3cc0f0907d
	   |-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
	   |-- fabric-object-builders-v0 0.7.3+3cc0f0907d
	   |-- fabric-particles-v1 0.2.5+3cc0f0907d
	   |-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
	   |-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
	   |-- fabric-renderer-indigo 0.4.5+3cc0f0907d
	   |-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
	   |-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
	   |-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
	   |-- fabric-rendering-v0 1.1.3+3cc0f0907d
	   |-- fabric-rendering-v1 1.6.1+3cc0f0907d
	   |-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	   |-- fabric-screen-api-v1 1.0.1+3cc0f0907d
	   |-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
	   |-- fabric-structure-api-v1 1.1.12+3cc0f0907d
	   |-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
	   |-- fabric-textures-v0 1.0.7+3cc0f0907d
	   |-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
	   \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 16
	- minecraft 1.16.5
[05:19:04] [main/INFO]: no good? no, this man is definitely up to evil.
[05:19:04] [main/WARN]: KnotClassLoader, you fool! Loading me was a grave mistake.
[05:19:04] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.16.5-loader.0.15.6-launcher.1.0.0.jar:1.0.0]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:473) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:352) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:115) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/fabricmc/loader/launch/knot/KnotClassLoader
	at net.devtech.grossfabrichacks.GrossFabricHacks.<clinit>(GrossFabricHacks.java:101) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:473) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:352) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:115) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/fabricmc/loader/launch/knot/KnotClassLoader
	at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.findAndDefineAndInitializeClass(UnsafeUtil.java:266) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.defineAndInitializeAndUnsafeCast(UnsafeUtil.java:109) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at net.devtech.grossfabrichacks.GrossFabricHacks.<clinit>(GrossFabricHacks.java:99) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:473) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:352) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:115) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
	... 1 more
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/loader/launch/knot/KnotClassLoader
	at jdk.internal.misc.Unsafe.defineClass0(Native Method) ~[?:?]
	at jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1325) ~[?:?]
	at net.gudenau.lib.unsafe.Unsafe.defineClass(Unsafe.java:554) ~[net_gudenau_lib_unsafe-1.4.3-28c52efc61495a46.jar:?]
	at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.defineClass(UnsafeUtil.java:237) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.findAndDefineClass(UnsafeUtil.java:246) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.findAndDefineAndInitializeClass(UnsafeUtil.java:264) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.defineAndInitializeAndUnsafeCast(UnsafeUtil.java:109) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at net.devtech.grossfabrichacks.GrossFabricHacks.<clinit>(GrossFabricHacks.java:99) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:473) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:352) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:115) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
	... 1 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.launch.knot.KnotClassLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:433) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at jdk.internal.misc.Unsafe.defineClass0(Native Method) ~[?:?]
	at jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1325) ~[?:?]
	at net.gudenau.lib.unsafe.Unsafe.defineClass(Unsafe.java:554) ~[net_gudenau_lib_unsafe-1.4.3-28c52efc61495a46.jar:?]
	at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.defineClass(UnsafeUtil.java:237) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.findAndDefineClass(UnsafeUtil.java:246) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.findAndDefineAndInitializeClass(UnsafeUtil.java:264) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at net.devtech.grossfabrichacks.unsafe.UnsafeUtil.defineAndInitializeAndUnsafeCast(UnsafeUtil.java:109) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at net.devtech.grossfabrichacks.GrossFabricHacks.<clinit>(GrossFabricHacks.java:99) ~[grossfabrichacks-6.1-JP7-4-f9bab6c4e9e9312f.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:473) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:352) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:115) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
	... 1 more

```

**Comment by John-Paul-R** [comment]
I need to go back and remove `GrossFabricHacks` from the latest 1.16.5 builds. Some of the APIs it uses are not available in modern Java versions (and, due to the way I compiled / the features I used, the original Java version that this mc 1.16.5 used also might not work... oops)

**Comment by John-Paul-R** [comment]
This'll have implications for command overloads (like same command, different arguments, and how they get resolved... (think how `/tp` can be `/tp x y z` or `/tp playerName`). EC does the same with some of its commands... _but_ I had to do a horrid modding of Brigadier, not Minecraft, to get this overloading to work the way it needed to. Which I couldn't do without `GrossFabricHacks` at the time. New strategy needed...
