### ISSUE TITLE
1.21 unsupported

### ISSUE THREAD

**Issue by Grandev-0** [John-Paul-R/Essential-Commands#284]
The mod is incompatible with 1.21 and I port would be much appreciated.
Here is the crash report of the mod along with stack deobfuscator and mixin trace:

`[10:20:02] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[10:20:02] [main/INFO]: Loading 50 mods:
	- essential_commands 0.35.0-rc1-mc1.20.6
	   |-- ec-core 1.3.0-mc1.20.6
	   |    |-- org_yaml_snakeyaml 2.0
	   |    |-- placeholder-api 2.4.0-pre.1+1.20.5
	   |    \-- playerabilitylib 1.9.0
	   |-- org_yaml_snakeyaml 2.0
	   |-- placeholder-api 2.4.0-pre.1+1.20.5
	   \-- playerabilitylib 1.9.0
	- fabric-api 0.100.1+1.21
	   |-- fabric-api-base 0.4.42+6573ed8c90
	   |-- fabric-api-lookup-api-v1 1.6.65+b559734490
	   |-- fabric-biome-api-v1 13.0.28+6fc22b9990
	   |-- fabric-block-api-v1 1.0.22+0af3f5a790
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c90
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a790
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c90
	   |-- fabric-command-api-v1 1.2.48+f71b366f90
	   |-- fabric-command-api-v2 2.2.27+6a6dfa1990
	   |-- fabric-commands-v0 0.2.65+df3654b390
	   |-- fabric-content-registries-v0 8.0.11+b559734490
	   |-- fabric-convention-tags-v1 2.0.12+7f945d5b90
	   |-- fabric-convention-tags-v2 2.2.1+d153f34490
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a790
	   |-- fabric-data-attachment-api-v1 1.1.22+6a6dfa1990
	   |-- fabric-data-generation-api-v1 20.2.6+16c4ae2590
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9990
	   |-- fabric-entity-events-v1 1.6.12+6fc22b9990
	   |-- fabric-events-interaction-v0 0.7.10+e633f88390
	   |-- fabric-game-rule-api-v1 1.0.52+6573ed8c90
	   |-- fabric-item-api-v1 11.0.0+afdfc92190
	   |-- fabric-item-group-api-v1 4.1.0+00ab0a6390
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a790
	   |-- fabric-keybindings-v0 0.2.45+df3654b390
	   |-- fabric-lifecycle-events-v1 2.3.9+98a7dbbb90
	   |-- fabric-loot-api-v2 3.0.9+6573ed8c90
	   |-- fabric-message-api-v1 6.0.13+6573ed8c90
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b90
	   |-- fabric-networking-api-v1 4.1.0+686dcdce90
	   |-- fabric-object-builder-api-v1 15.1.10+d132107690
	   |-- fabric-particles-v1 4.0.2+6573ed8c90
	   |-- fabric-recipe-api-v1 5.0.8+6573ed8c90
	   |-- fabric-registry-sync-v0 5.0.21+b9828ba390
	   |-- fabric-renderer-api-v1 3.2.16+fe474d6b90
	   |-- fabric-renderer-indigo 1.6.3+cc9f121a90
	   |-- fabric-renderer-registries-v1 3.2.66+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e90
	   |-- fabric-rendering-fluids-v1 3.1.6+b559734490
	   |-- fabric-rendering-v0 1.1.69+df3654b390
	   |-- fabric-rendering-v1 5.0.3+d132107690
	   |-- fabric-resource-conditions-api-v1 4.2.1+d153f34490
	   |-- fabric-resource-loader-v0 1.1.3+b559734490
	   |-- fabric-screen-api-v1 2.0.24+b559734490
	   |-- fabric-screen-handler-api-v1 1.3.78+b559734490
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c90
	   |-- fabric-transfer-api-v1 5.1.12+b559734490
	   \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8c90
	- fabric-permissions-api-v0 0.3.1
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 22
	- minecraft 1.21
	- mixintrace 1.1.1+1.17
	- stackdeobfuscator 1.4.2+bf1fc22
	   |-- dev_booky_common_ 1.4.2+bf1fc22
	   \-- net_fabricmc_mapping-io 0.3.0
[10:20:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[10:20:02] [main/INFO]: Compatibility level set to JAVA_17
[10:20:03] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[10:20:07] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.minecraft.class_1299.<clinit>(class_1299.java:224) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:854) ~[server-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:64) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1058) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1054) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:355) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1341) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:869) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1259) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:224) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:854) ~[server-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:64) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1058) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1054) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:355) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1341) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:869) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1259) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:224) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:854) ~[server-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:64) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1058) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1054) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:355) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1341) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:869) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1259) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onTeleportBetweenWorlds(Lnet/minecraft/class_3218;DDDFFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3218;Lnet/minecraft/class_5217;)V in essential_commands.mixins.json:ServerPlayerEntityMixin from mod essential_commands failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap essential_commands-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:224) ~[server-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:854) ~[server-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:64) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1058) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1054) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:355) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1341) ~[server-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:869) ~[server-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1259) ~[server-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
`

**Comment by John-Paul-R** [comment]
It's in the oven! Will be released today. You can download an experimental build from the "artifacts" here: https://github.com/John-Paul-R/Essential-Commands/actions/runs/9509189028

**Comment by John-Paul-R** [comment]
mc 1.21 is supported in the latest release! ([0.35.2-mc1.21](https://github.com/John-Paul-R/Essential-Commands/releases/tag/0.35.2-mc1.21))
