### ISSUE TITLE
[Bug] Rules command does not work

### ISSUE THREAD

**Issue by burdoto** [John-Paul-R/Essential-Commands#292]
The rules command is currently broken as of version 0.35.3-1.20.1

Issuing `/rules` crashes the clientside connection with the message:
```
Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException: Received unexpected null component
```

Upon trying to issue `/rules reload`, the server throws a parsing exception with no further detail:
```
[STDERR]: java.nio.charset.MalformedInputException: Input length = 1
[STDERR]:         at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
[STDERR]:         at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:337)
[STDERR]:         at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:189)
[STDERR]:         at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
[STDERR]:         at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
[STDERR]:         at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
[STDERR]:         at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
[STDERR]:         at java.base/java.nio.file.Files.readAllLines(Files.java:3415)
[STDERR]:         at java.base/java.nio.file.Files.readAllLines(Files.java:3453)
[STDERR]:         at com.fibermc.essentialcommands.commands.RulesCommand.reload(RulesCommand.java:51)
[STDERR]:         at com.fibermc.essentialcommands.commands.RulesCommand.reloadCommand(RulesCommand.java:34)
[STDERR]:         at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[STDERR]:         at net.minecraft.class_2170.redirect$zim000$architectury$performCommand(class_2170.java:545)
[STDERR]:         at net.minecraft.class_2170.method_9249(class_2170.java:287)
[STDERR]:         at net.minecraft.class_3244.method_45010(class_3244.java:1341)
[STDERR]:         at net.minecraft.class_3244.method_44356(class_3244.java:1321)
[STDERR]:         at net.minecraft.class_1255.method_5386(class_1255.java:67)
[STDERR]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[STDERR]:         at net.minecraft.class_3738.run(class_3738.java:18)
[STDERR]:         at net.minecraft.class_1255.method_18859(class_1255.java:156)
[STDERR]:         at net.minecraft.class_4093.method_18859(class_4093.java:23)
[STDERR]:         at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
[STDERR]:         at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
[STDERR]:         at net.minecraft.class_1255.method_16075(class_1255.java:130)
[STDERR]:         at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:12318)
[STDERR]:         at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
[STDERR]:         at net.minecraft.class_1255.method_5383(class_1255.java:115)
[STDERR]:         at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
[STDERR]:         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
[STDERR]:         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[STDERR]:         at java.base/java.lang.Thread.run(Thread.java:840)
```

The rules file in question is formatted in plaintext using `§`-based color codes.

**Comment by John-Paul-R** [comment]
Hm, sorry this has taken so long to get back to you. I have a painful feeling this might be text encoding related.

the following `rules.txt` works for me

```
§3The rules are simple!

```

This is written as a UTF-8 file with LF line endings on my machine, though.

Do you have an example problematic file?
