### ISSUE TITLE
[Bug][Crash]After adding the mod, both the server and the single game will crash!

### ISSUE THREAD

**Issue by VV46678** [John-Paul-R/Essential-Commands#293]
Perhaps version 1.16.5 is a bit outdated, but there are still many players who enjoy this version,So please fix it! I really really want it! we need you! qwq

The crash log.
```
[16:37:25] [main/ERROR]: no good? no, this man is definitely up to evil.
[16:37:25] [main/INFO]: this is more concerning than Fabric Zero
[16:37:25] [main/INFO]: no gross_agent.jar found, cloning new one
[16:37:25] [main/INFO]: VM name: 12704@VV-Server
[16:37:25] [main/INFO]: VM PID: 12704
[16:37:25] [main/INFO]: Attaching to VM
[16:37:25] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.devtech.grossfabrichacks.reflection.AccessAllower.makeAccessibleObjectAccessible(AccessAllower.java:26) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at net.devtech.grossfabrichacks.reflection.AccessAllower.init(AccessAllower.java:19) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at net.devtech.grossfabrichacks.GrossFabricHacks.<clinit>(GrossFabricHacks.java:27) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:488) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:473) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:352) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:115) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: can't load class gross.agent.InstrumentationAgent at D:\VV's MC Server\gross_hacks\gross_agent.jar as it hasn't been exposed to the game (yet? The system property fabric.classPathGroups may not be set correctly in-dev)
	at net.devtech.grossfabrichacks.instrumentation.InstrumentationApi.getInstrumentation(InstrumentationApi.java:113) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at net.devtech.grossfabrichacks.instrumentation.InstrumentationApi.<clinit>(InstrumentationApi.java:191) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at net.devtech.grossfabrichacks.reflection.AccessAllower.makeAccessibleObjectAccessible(AccessAllower.java:26) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at net.devtech.grossfabrichacks.reflection.AccessAllower.init(AccessAllower.java:19) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at net.devtech.grossfabrichacks.GrossFabricHacks.<clinit>(GrossFabricHacks.java:27) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:488) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:473) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:352) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:115) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.ClassNotFoundException: can't load class gross.agent.InstrumentationAgent at D:\VV's MC Server\gross_hacks\gross_agent.jar as it hasn't been exposed to the game (yet? The system property fabric.classPathGroups may not be set correctly in-dev)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:240) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:383) ~[?:?]
	at java.lang.Class.forName(Class.java:376) ~[?:?]
	at net.devtech.grossfabrichacks.instrumentation.InstrumentationApi.getInstrumentation(InstrumentationApi.java:109) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at net.devtech.grossfabrichacks.instrumentation.InstrumentationApi.<clinit>(InstrumentationApi.java:191) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at net.devtech.grossfabrichacks.reflection.AccessAllower.makeAccessibleObjectAccessible(AccessAllower.java:26) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at net.devtech.grossfabrichacks.reflection.AccessAllower.init(AccessAllower.java:19) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at net.devtech.grossfabrichacks.GrossFabricHacks.<clinit>(GrossFabricHacks.java:27) ~[grossfabrichacks-6.1-f358305bd42b0991.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:488) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:473) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:352) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:115) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
```

The following is a list of mods:

```
[16:37:20] [main/INFO]: Loading 163 mods:
	- alloy_forgery 1.2.0
	- animal_feeding_trough 1.0.2
	- appleskin 2.5.1+mc1.16.5
	- awesomedungeonend 3.1.1
	- bclib 0.1.45
	- better_log4j_config 1.2.0
	- bettercaves 1.16.5-1.2
	- betterdungeons 1.16.5-1.0.1
	- bettermineshafts 1.16.4-1.0.2
	   \-- autoconfig1u 3.3.1
	- betternether 5.0.7
	- betterstrongholds 1.16.5-1.1.1
	- betterthanmending 1.3.0
	- bettervillage 3.1.0
	- byg 1.3.6
	   |-- com_electronwill_night-config_core 3.6.2
	   \-- com_electronwill_night-config_toml 3.6.2
	- cardinal-components 2.8.3
	   |-- cardinal-components-base 2.8.3
	   |-- cardinal-components-block 2.8.3
	   |-- cardinal-components-chunk 2.8.3
	   |-- cardinal-components-entity 2.8.3
	   |-- cardinal-components-item 2.8.3
	   |-- cardinal-components-level 2.8.3
	   |-- cardinal-components-scoreboard 2.8.3
	   |-- cardinal-components-util 2.8.3
	   \-- cardinal-components-world 2.8.3
	- charm 2.3.2
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- cloth-api 1.6.59
	   |-- cloth-armor-api-v1 1.6.59
	   |-- cloth-client-events-v0 1.6.59
	   |-- cloth-common-events-v1 1.6.59
	   |-- cloth-datagen-api-v1 1.6.59
	   |-- cloth-durability-bar-api-v1 1.6.59
	   |-- cloth-dynamic-registry-api-v1 1.6.59
	   |-- cloth-scissors-api-v1 1.6.59
	   \-- cloth-utils-v1 1.6.59
	- cloth-config2 4.17.101
	   \-- cloth-basic-math 0.6.1
	- cmdspy 1.2.2-1.16.5
	- collective-fabric 5.50
	   \-- fiber 0.23.0-2
	- curios 0.0.13-1.16.5
	- curiouselytra 1.1.1-1.16.5
	   \-- caelus 0.0.15-1.16.4
	- dungeons_arise 1.16.5-2.1.47-fabric
	- easyelytratakeoff-fabric 3.2
	- enderitemod 1.2.4
	- essential_commands 0.13.4-beta+1-mc1.16.5
	   |-- fabric-permissions-api-v0 0.1-SNAPSHOT
	   |-- grossfabrichacks 6.1
	   \-- placeholder-api 1.0.1+1.16
	- fabric 0.42.0+1.16
	   |-- fabric-api-base 0.4.0+3cc0f0907d
	   |-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
	   |-- fabric-biome-api-v1 3.1.13+3cc0f0907d
	   |-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
	   |-- fabric-command-api-v1 1.1.3+3cc0f0907d
	   |-- fabric-commands-v0 0.2.3+3cc0f0907d
	   |-- fabric-containers-v0 0.1.12+3cc0f0907d
	   |-- fabric-content-registries-v0 0.2.5+3cc0f0907d
	   |-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
	   |-- fabric-dimensions-v1 2.0.8+3cc0f0907d
	   |-- fabric-entity-events-v1 1.2.4+3cc0f0907d
	   |-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
	   |-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
	   |-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
	   |-- fabric-item-api-v1 1.2.2+3cc0f0907d
	   |-- fabric-item-groups-v0 0.3.1+3cc0f0907d
	   |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-keybindings-v0 0.2.2+3cc0f0907d
	   |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
	   |-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
	   |-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
	   |-- fabric-models-v0 0.3.1+3cc0f0907d
	   |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
	   |-- fabric-networking-v0 0.3.3+3cc0f0907d
	   |-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
	   |-- fabric-object-builders-v0 0.7.3+3cc0f0907d
	   |-- fabric-particles-v1 0.2.5+3cc0f0907d
	   |-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
	   |-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
	   |-- fabric-renderer-indigo 0.4.5+3cc0f0907d
	   |-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
	   |-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
	   |-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
	   |-- fabric-rendering-v0 1.1.3+3cc0f0907d
	   |-- fabric-rendering-v1 1.6.1+3cc0f0907d
	   |-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	   |-- fabric-screen-api-v1 1.0.1+3cc0f0907d
	   |-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
	   |-- fabric-structure-api-v1 1.1.12+3cc0f0907d
	   |-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
	   |-- fabric-textures-v0 1.0.7+3cc0f0907d
	   |-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
	   \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- fancyclear 1.3.1
	- farmersdelight 1.16.5-0.0.7
	- ferritecore 2.1.1
	- grindenchantments 1.1.3+1.16.3
	- immersive_aircraft 0.5.2+1.16.5
	- immersive_armors 1.5.1+1.16.5
	- inventorytotem-fabric 2.2
	- invview 1.4.1-1.16.4+
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- java 18
	- jline4mcdsrv 0.5.0
	   |-- org_jline_jline 3.25.1
	   \-- org_jline_jline-terminal-jansi 3.25.1
	- krypton 0.1.2
	- libraryferret 4.0.0
	- lithium 0.6.6
	- logbegone 1.0.4
	- login 1.0.0
	- luckperms 5.3.9
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- lucky 1.16.5-5
	- minecraft 1.16.5
	- minecraft-command-permissions 1.0.2
	- modernfix 5.18.0+mc1.16.5
	- mythicmetals 0.9.11
	   \-- enchant_giver 1.0.3
	- netherite_nugget 1.2.1
	   \-- autoconfig1u 3.3.1
	- netherite_plus 1.4.5-1.16.5
	   |-- architectury 1.9.136
	   |-- multi_item_lib 1.3.0
	   \-- oro_config 3.0.0
	- phosphor 0.8.0
	- player_events 2.1.1
	   \-- player_events_api 2.1.1
	- searchlight 1.1.1
	- sihywtcamd 1.5.2+1.16.5
	- sleepwarp 1.2.0+1.16.5
	- spark 1.6.0
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- spawnermod 1.1.2
	- styledplayerlist 1.2.1
	   |-- adventure-platform-fabric 4.0.0-SNAPSHOT
	   |    |-- net_kyori_adventure-api 4.7.0
	   |    |-- net_kyori_adventure-key 4.7.0
	   |    |-- net_kyori_adventure-platform-api 4.0.0-SNAPSHOT
	   |    |-- net_kyori_adventure-text-feature-pagination 4.0.0-SNAPSHOT
	   |    |-- net_kyori_adventure-text-serializer-gson 4.7.0
	   |    |-- net_kyori_adventure-text-serializer-plain 4.7.0
	   |    |-- net_kyori_examination-api 1.1.0
	   |    \-- net_kyori_examination-string 1.1.0
	   |-- fabric-permissions-api-v0 0.1-SNAPSHOT
	   \-- net_kyori_adventure-text-minimessage 4.1.0-SNAPSHOT
	- taxfreelevels 1.3-1.16.5
	- textile_backup 2.2.0-1.16
	   |-- com_github_shevek_parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
	   |-- org_apache_commons_commons-compress 1.19
	   \-- org_tukaani_xz 1.8
	- tiered 1.2.2-beta-1.16.4
	- totemmod 0.3.2
	- totemplus 1.1-1.16.5
	- travelersbackpack 1.16.5-5.4.38
	   \-- reach-entity-attributes 1.1.1
	- veinmining 0.0.12-1.16.5
	   |-- autoconfig1u 3.3.1
	   |-- fabric-api-base 0.4.0+3cc0f0907d
	   |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
	   |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
	   \-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	- weaponmaster 3.0.2
	- whyamionfire 1.1.1
	- worldedit 7.2.5+57d5ac9
	- yungsapi 1.16.5-Fabric-9
```

**Comment by John-Paul-R** [comment]
I believe this particular error can be resolved by running with Java 8

Closing as "work-around-able". I should release a non-GrossFabricHacks version as tracked in #295, though.
