### ISSUE TITLE
[0.17.1-mc1.18-rc3] Server crash on player join if `use_permissions_api=true`

### ISSUE THREAD

**Issue by Mr-Rixa** [John-Paul-R/Essential-Commands#80]
Server crashes when a player joins IF **use permissions api is set to true**

Fabric Loader 0.12.8
FabricApi 0.44.0+1.18
LuckPerms 5.3.86
Essential Commands 0.17.1-mc1.18-rc3

```
Description: Exception in server tick loop

java.lang.StackOverflowError: Exception in server tick loop
        at net.minecraft.class_3326.method_14619(class_3326.java:36)
        at net.minecraft.class_3326.method_14634(class_3326.java:9)
        at net.minecraft.class_3331.method_14644(class_3331.java:82)
        at net.minecraft.class_3324.method_14569(class_3324.java:644)
        at net.minecraft.server.MinecraftServer.method_3835(MinecraftServer.java:1439)
        at net.minecraft.class_3222.method_5691(class_3222.java:1388)
        at net.minecraft.class_1297.method_5671(class_1297.java:2975)
        at me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:183)
        at net.minecraft.class_2168.handler$zno000$hasPermission(class_2168.java:522)
        at net.minecraft.class_2168.method_9259(class_2168.java:180)
        at com.fibermc.essentialcommands.ECPerms.isSuperAdmin(ECPerms.java:78)
        at com.fibermc.essentialcommands.ECPerms.lambda$init$0(ECPerms.java:69)
        at me.lucko.fabric.api.permissions.v0.PermissionCheckEvent.lambda$static$0(PermissionCheckEvent.java:42)
        at me.lucko.fabric.api.permissions.v0.Permissions.getPermissionValue(Permissions.java:53)
        at me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:91)
        at me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:183)
        at net.minecraft.class_2168.handler$zno000$hasPermission(class_2168.java:522)
        at net.minecraft.class_2168.method_9259(class_2168.java:180)
        at com.fibermc.essentialcommands.ECPerms.isSuperAdmin(ECPerms.java:78)
        at com.fibermc.essentialcommands.ECPerms.lambda$init$0(ECPerms.java:69)
        at me.lucko.fabric.api.permissions.v0.PermissionCheckEvent.lambda$static$0(PermissionCheckEvent.java:42)
        at me.lucko.fabric.api.permissions.v0.Permissions.getPermissionValue(Permissions.java:53)
        at me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:91)
        at me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:183)
        at net.minecraft.class_2168.handler$zno000$hasPermission(class_2168.java:522)
        at net.minecraft.class_2168.method_9259(class_2168.java:180)
        at com.fibermc.essentialcommands.ECPerms.isSuperAdmin(ECPerms.java:78)
        at com.fibermc.essentialcommands.ECPerms.lambda$init$0(ECPerms.java:69)
[snip ~800 lines looping]
        at com.fibermc.essentialcommands.ECPerms.isSuperAdmin(ECPerms.java:78)
        at com.fibermc.essentialcommands.ECPerms.lambda$init$0(ECPerms.java:69)
        at me.lucko.fabric.api.permissions.v0.PermissionCheckEvent.lambda$static$0(PermissionCheckEvent.java:42)
        at me.lucko.fabric.api.permissions.v0.Permissions.getPermissionValue(Permissions.java:53)
        at me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:91)
        at me.lucko.fabric.api.permissions.v0.Permissions.check(Permissions.java:183)

```

**Comment by John-Paul-R** [comment]
Currently cannot reproduce. Server config I am using for testing: [[.zip file](https://drive.google.com/file/d/1Bshtpf8EgoK1fW0Iq9crlcjQzb2qWbVn/view?usp=sharing)]

Let me know if this works for you?

**Comment by John-Paul-R** [comment]
Closing due to inactivity. Feel free to reopen if this issue is still being encountered on modern versions of EC.
